site_name: My Project Documentationtheme:  name: material  # Use Material theme (optional)nav:  - Home: index.md
  - Scripts:
    - ScreenRNSA: screenrnsa.md
    - ScreenByRepTime: screenbyreptime.md  #- Pipeline: pipeline.md  #- Script: script.md

